[project]
name = "agents-course-huggingface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=0.29.1",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
